### ISSUE TITLE
Ability to query specific OC properties

### ISSUE THREAD

**Issue by PVince81** [owncloud/js-owncloud-client#25]
Add an optional argument to `oc.files.list()` to specify a list of properties (with namespace) to retrieve.
These properties must be passed in the PROPFIND body as XML to tell the server we want those.

This would make it possible to query more properties like "oc:fileid" (aka "{http://owncloud.org/ns}fileid")

**Comment by PVince81** [comment]
and extend the `FileInfo` class to allow accessing those extra properties / arbitrary properties with `fileInfo.getProperty('{http://owncloud.org/ns}fileid')`

**Comment by PVince81** [comment]
Raised as https://github.com/owncloud/js-owncloud-client/issues/94 to do the switch.

**Comment by DeepDiver1975** [comment]
fixed with #95
