### ISSUE TITLE
Switch to davclient.js

### ISSUE THREAD

**Issue by PVince81** [owncloud/js-owncloud-client#94]
Switch all Webdav code to use [davclient.js](https://github.com/owncloud/davclient.js).

This is mostly important for PROPFIND and PROPPATCH as the code is compatible with both node JS and browser and provides ways to serialize and deserialize the requests/responses and takes care of escaping, etc.

**Comment by DeepDiver1975** [comment]
Findings:
- davclient.js cannot be required - module exports are missing -> https://github.com/owncloud/davclient.js/pull/35
- davclient.js uses XMLHttpRequest which does no exist in nodejs - will use node pollifil for now

PR should come asap

**Comment by DeepDiver1975** [comment]
fixes with #110
