### ISSUE TITLE
Login fails when disclaimer is required

### ISSUE THREAD

**Issue by exception2398** [owncloud/js-owncloud-client#98]
Our organisation requires to accept a disclaimer (privacy agreement) before login.
This leads to the login method throwing the error: 'Unauthorized', regardless of using the user password or a new created app password. 

If this is not an issue, please correct me, I'm new here. Thanks

**Comment by PVince81** [comment]
How is the disclaimer implemented ?

As far as I understand this is using basic auth on the Webdav endpoint.

It is possible that the Webdav endpoint does not allow logging in until the disclaimer was displayed. In this case the library must be able to fail gracefully.

**Comment by exception2398** [comment]
It's a "Agree Disclaimer" which - on the login page - looks like this:
<img width="288" alt="screen shot 2018-09-25 at 00 49 50" src="https://user-images.githubusercontent.com/43410822/45983680-eddd6080-c05d-11e8-8bf9-f97802ff95d1.png">

User selection could be saved in cookies but this option is deactivated.

After we required users to accept the disclaimer, the official OwnCloud App would only work with self generated "App Password" but not with "classical" login data.
I hope this helps.

**Comment by DeepDiver1975** [comment]
js-owncloud-client now supports oauth bearer tokens. You should implement an oauth flow in your application which will redirect to the regular owncloud login which will display the disclaimer and also will trigger any 2fa plugins or what so ever ....

Closing this therefore ... THX
